networks:
  cicero:
    driver: bridge

services:
  gnuradio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnuradio-novnc
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - UDEV=1 # To ensure udev works inside the container
    networks:
      - cicero
    volumes:
      - ~/cicero/novnc/home/guser:/home/guser
      - ~/cicero/gnuradio:/app
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Pass USB devices
    ports:
      - "8090:8080"
    stdin_open: true
    tty: true
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864